DROP TABLE IF EXISTS autos;
DROP TABLE IF EXISTS clients ;

CREATE TABLE clients (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR (255) NOT NULL,
  birthday DATE NOT NULL ,
  PRIMARY KEY (id));

ALTER TABLE clients AUTO_INCREMENT=0;

CREATE TABLE autos (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  birthday DATE NOT NULL ,
  PRIMARY KEY (id));

ALTER TABLE autos ADD client_id INTEGER UNIQUE ;
ALTER TABLE autos ADD CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE;

ALTER TABLE autos AUTO_INCREMENT=0;



